inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake' # 初期設定なので除外

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Style/StringConcatenation:
  Exclude:
    - 'config/initializers/rswag_api.rb'
